// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © PaulMclachlan
//@version=5
strategy("BLSH-S", overlay=true, margin_long=100, margin_short=100, calc_on_every_tick = true)
//indicator(title="Buy Low Sell High Composite", shorttitle="BLSH")

source = input.source(defval=ohlc4, title="Source")
EMA_length = input.int(5, title = "EMA length")
tp = input.float(0, title = "Transparency", minval=0, maxval=100)
visible = input.bool(defval=false, title = "Show only near-timeframe EMAs")




// normalize values into the range -1 to +1
normalize(value, minValue, maxValue) =>
    var_range = maxValue - minValue == 0 ? 0.0001 : maxValue - minValue
    -1 + (((value - minValue) / var_range) * 2)

atrValue = ta.atr(9)
priceRange = 2 * atrValue

// RSI
rsiValue = ta.rsi(close, 14)
rsiValueNormalized = normalize(rsiValue, 25, 75)
rsiColor = rsiValueNormalized <= 0 ? color.orange : color.yellow

// Elliot Wave
emaDiff = ta.ema(close, 5) - ta.ema(close, 35)
emaDiffNormalized = normalize(emaDiff, -priceRange, priceRange)
emaColor = emaDiff <= 0 ? color.red : color.lime

// MACD
fastMovingAverage = ta.ema(close, 12)
slowMovingAverage = ta.ema(close, 26)
macd = fastMovingAverage - slowMovingAverage
macdSignal = ta.sma(macd, 9)
macdHistogram = macd - macdSignal
macdNormalized = normalize(macd, -priceRange, priceRange)
macdSignalNormalized = normalize(macdSignal, -priceRange, priceRange)
macdHistogramNormalized = normalize(macdHistogram, -priceRange, priceRange)

isMACDAbove = macd >= macdSignal
crossoverColor = isMACDAbove ? color.lime : color.red
crossoverValue = ta.cross(macd, macdSignal) ? macdSignalNormalized : na

// MFI
positiveFlow = math.sum(volume * (ta.change(hlc3) <= 0 ? 0 : hlc3), 14)
negativeFlow = int(math.sum(volume * (ta.change(hlc3) >= 0 ? 0 : hlc3), 14))
//mfiValue = ta.rsi(positiveFlow, negativeFlow)
// https://www.tradingview.com/pine-script-docs/en/v5/migration_guides/v4_to_v5_migration_guide.html?highlight=mfi
mfiValue = 100.0 - (100.0 / (1.0 + positiveFlow / negativeFlow))
mfiValueNormalized = normalize(mfiValue, 25, 75)

// Composite
compositeValue = emaDiffNormalized + rsiValueNormalized + macdHistogramNormalized + mfiValueNormalized
compositeNormalized = normalize(compositeValue, -4, 4)
compositeColor = compositeValue <= 0 ? color.red : color.lime
compositeStyle = plot.style_histogram

// Plots
//plot(compositeNormalized, title="Composite", color=color.new(compositeColor, 50), style=plot.style_area, linewidth=2)
plot(macdSignalNormalized, title="MacD Signal", style=plot.style_line, linewidth=1, color=crossoverColor)
//plot(crossoverValue, title="Crossover", style=plot.style_circles, linewidth=3, color=crossoverColor)

// END indicator(title="Buy Low Sell High Composite", shorttitle="BLSH pmac")



//timeframe.change("30")
//ema30 = ta.ema(compositeNormalized,5)
//tf = input.timeframe(title="Timeframe", defval="30")
//s1 = request.security(syminfo.tickerid, tf, compositeNormalized, gaps=barmerge.gaps_on)
//ma_len = input(title="Length", defval=100)
//src = input(title="Source", type=source, defval=close)
//plot(ema30, title="Ema 30min", color=color.yellow)


// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Snufkin420TC
// Developed with Dumpster Capital and published sans secret sauce

// START indicator("EMA", overlay=true)

// Create non-repainting security function
fix_security(_symbol, _res, _src) =>
    request.security(_symbol, _res, _src[barstate.isrealtime ? 1 : 0], gaps=barmerge.gaps_on, lookahead=barmerge.lookahead_off)

// Select which EMAs to plot
string EMAs = input.string("Standard", title = "EMAs to show", options = ["Standard", "Fibonacci"])

// User settings

//get Timeframe of current chart and convert to a score for timeframe detection based switches
timeframe = timeframe.period
framescore = 0
framescore := if (timeframe == "M")
    13
else if (timeframe == "W")
    12
else if (timeframe == "D")
    11
else if (timeframe == "240")
    10
else if (timeframe == "180")
    9
else if (timeframe == "120")
    8
else if (timeframe == "60")
    7
else if (timeframe == "45")
    6
else if (timeframe == "30")
    5
else if (timeframe == "15")
    4
else if (timeframe == "5")
    3
else if (timeframe == "3")
    2
else if (timeframe == "1")
    1
else
    0

//Initialize EMAs
EMA1 = 0.0
EMA2 = 0.0
EMA3 = 0.0
EMA4 = 0.0
EMA5 = 0.0
EMA6 = 0.0
EMA7 = 0.0
EMA8 = 0.0
EMA9 = 0.0
EMA10 = 0.0
EMA11 = 0.0
EMA12 = 0.0
EMA13 = 0.0
EMA14 = 0.0
EMA15 = 0.0
EMA16 = 0.0

// Calculate EMAs
if (EMAs == 'Standard' and visible == false)
    EMA1 := (framescore <= 1) ? fix_security(syminfo.tickerid, '1', ta.ema(source,EMA_length)) : na
    EMA2 := (framescore <= 2) ? fix_security(syminfo.tickerid, '3', ta.ema(source,EMA_length)) : na
    EMA3 := (framescore <= 3) ? fix_security(syminfo.tickerid, '5', ta.ema(source,EMA_length)) : na
    EMA4 := (framescore <= 4) ? fix_security(syminfo.tickerid, '15', ta.ema(source,EMA_length)) : na
    EMA5 := (framescore <= 5) ? fix_security(syminfo.tickerid,'30', ta.ema(source,EMA_length)) : na
    EMA6 := (framescore <= 7) ? fix_security(syminfo.tickerid,'60', ta.ema(source,EMA_length)) : na
    EMA7 := (framescore <= 8) ? fix_security(syminfo.tickerid, '120', ta.ema(source,EMA_length)) : na
    EMA8 := (framescore <= 10) ? fix_security(syminfo.tickerid, '240', ta.ema(source,EMA_length)) : na
    EMA9 := (framescore <= 10) ? fix_security(syminfo.tickerid, '480', ta.ema(source,EMA_length)) : na
    EMA10 := (framescore <= 11) ? fix_security(syminfo.tickerid, 'D', ta.ema(source,EMA_length)) : na
    EMA11 := (framescore <= 12) ? fix_security(syminfo.tickerid, 'W', ta.ema(source,EMA_length)) : na
    EMA12 := (framescore <= 13) ? fix_security(syminfo.tickerid, 'M', ta.ema(source,EMA_length)) : na
    EMA13 := (framescore <= 14) ? fix_security(syminfo.tickerid, '3M', ta.ema(source,EMA_length)) : na
    EMA14 := na
    EMA15 := na
    EMA16 := na
if (EMAs == 'Standard' and visible == true)
    EMA1 := (framescore <= 1) ? fix_security(syminfo.tickerid, '1', ta.ema(source,EMA_length)) : na
    EMA2 := (framescore <= 2) ? fix_security(syminfo.tickerid, '3', ta.ema(source,EMA_length)) : na
    EMA3 := (framescore <= 3) ? fix_security(syminfo.tickerid, '5', ta.ema(source,EMA_length)) : na
    EMA4 := (framescore <= 4) ? fix_security(syminfo.tickerid, '15', ta.ema(source,EMA_length)) : na
    EMA5 := (framescore <= 5) ? fix_security(syminfo.tickerid,'30', ta.ema(source,EMA_length)) : na
    EMA6 := (framescore <= 7) ? fix_security(syminfo.tickerid,'60', ta.ema(source,EMA_length)) : na
    EMA7 := (framescore <= 8 and framescore > 1) ? fix_security(syminfo.tickerid, '120', ta.ema(source,EMA_length)) : na
    EMA8 := (framescore <= 10 and framescore > 3) ? fix_security(syminfo.tickerid, '240', ta.ema(source,EMA_length)) : na
    EMA9 := (framescore <= 10 and framescore > 3) ? fix_security(syminfo.tickerid, '480', ta.ema(source,EMA_length)) : na
    EMA10 := (framescore <= 11 and framescore > 4) ? fix_security(syminfo.tickerid, 'D', ta.ema(source,EMA_length)) : na
    EMA11 := (framescore <= 12 and framescore > 5) ? fix_security(syminfo.tickerid, 'W', ta.ema(source,EMA_length)) : na
    EMA12 := (framescore <= 13 and framescore > 6) ? fix_security(syminfo.tickerid, 'M', ta.ema(source,EMA_length)) : na
    EMA13 := (framescore <= 14 and framescore > 7) ? fix_security(syminfo.tickerid, '3M', ta.ema(source,EMA_length)) : na
    EMA14 := na
    EMA15 := na
    EMA16 := na
else if (EMAs == 'Fibonacci' and visible == false)
    EMA1 := (framescore <= 1) ? fix_security(syminfo.tickerid, '1', ta.ema(source,EMA_length)) : na
    EMA2 := (framescore <= 1) ? fix_security(syminfo.tickerid, '2', ta.ema(source,EMA_length)) : na
    EMA3 := (framescore <= 2) ? fix_security(syminfo.tickerid, '3', ta.ema(source,EMA_length)) : na
    EMA4 := (framescore <= 3) ? fix_security(syminfo.tickerid,'5', ta.ema(source,EMA_length)) : na
    EMA5 := (framescore <= 3) ? fix_security(syminfo.tickerid, '8', ta.ema(source,EMA_length)) : na
    EMA6 := (framescore <= 3) ? fix_security(syminfo.tickerid, '13', ta.ema(source,EMA_length)) : na
    EMA7 := (framescore <= 4) ? fix_security(syminfo.tickerid, '21', ta.ema(source,EMA_length)) : na
    EMA8 := (framescore <= 5) ? fix_security(syminfo.tickerid, '34', ta.ema(source,EMA_length)) : na
    EMA9 := (framescore <= 6) ? fix_security(syminfo.tickerid, '55', ta.ema(source,EMA_length)) : na
    EMA10 := (framescore <= 7) ? fix_security(syminfo.tickerid, '89', ta.ema(source,EMA_length)) : na
    EMA11 := (framescore <= 8) ? fix_security(syminfo.tickerid, '144', ta.ema(source,EMA_length)) : na
    EMA12 := (framescore <= 9) ? fix_security(syminfo.tickerid, '233', ta.ema(source,EMA_length)) : na
    EMA13 := (framescore <= 10) ? fix_security(syminfo.tickerid, '377', ta.ema(source,EMA_length)) : na
    EMA14 := (framescore <= 10) ? fix_security(syminfo.tickerid, '610', ta.ema(source,EMA_length)) : na
    EMA15 := (framescore <= 10) ? fix_security(syminfo.tickerid, '987', ta.ema(source,EMA_length)) : na
    EMA16 := (framescore <= 11) ? fix_security(syminfo.tickerid, 'D', ta.ema(source,EMA_length)) : na
else if (EMAs == 'Fibonacci' and visible == true)
    EMA1 := (framescore <= 1) ? fix_security(syminfo.tickerid, '1', ta.ema(source,EMA_length)) : na
    EMA2 := (framescore <= 1) ? fix_security(syminfo.tickerid, '2', ta.ema(source,EMA_length)) : na
    EMA3 := (framescore <= 2) ? fix_security(syminfo.tickerid, '3', ta.ema(source,EMA_length)) : na
    EMA4 := (framescore <= 3) ? fix_security(syminfo.tickerid,'5', ta.ema(source,EMA_length)) : na
    EMA5 := (framescore <= 3) ? fix_security(syminfo.tickerid, '8', ta.ema(source,EMA_length)) : na
    EMA6 := (framescore <= 3) ? fix_security(syminfo.tickerid, '13', ta.ema(source,EMA_length)) : na
    EMA7 := (framescore <= 4) ? fix_security(syminfo.tickerid, '21', ta.ema(source,EMA_length)) : na
    EMA8 := (framescore <= 5) ? fix_security(syminfo.tickerid, '34', ta.ema(source,EMA_length)) : na
    EMA9 := (framescore <= 6) ? fix_security(syminfo.tickerid, '55', ta.ema(source,EMA_length)) : na
    EMA10 := (framescore <= 7) ? fix_security(syminfo.tickerid, '89', ta.ema(source,EMA_length)) : na
    EMA11 := (framescore <= 8 and framescore > 1) ? fix_security(syminfo.tickerid, '144', ta.ema(source,EMA_length)) : na
    EMA12 := (framescore <= 9 and framescore > 2) ? fix_security(syminfo.tickerid, '233', ta.ema(source,EMA_length)) : na
    EMA13 := (framescore <= 10 and framescore > 3) ? fix_security(syminfo.tickerid, '377', ta.ema(source,EMA_length)) : na
    EMA14 := (framescore <= 10 and framescore > 3) ? fix_security(syminfo.tickerid, '610', ta.ema(source,EMA_length)) : na
    EMA15 := (framescore <= 10 and framescore > 3) ? fix_security(syminfo.tickerid, '987', ta.ema(source,EMA_length)) : na
    EMA16 := (framescore <= 11 and framescore > 4) ? fix_security(syminfo.tickerid, 'D', ta.ema(source,EMA_length)) : na

//Default rainbow coloring
// col1 = color.new(color.silver, tp)
// col2 = color.new(color.lime, tp)
// col3 = color.new(color.yellow, tp)
// col4 = color.new(color.orange, tp)
col5 = color.new(color.yellow, tp)
// col6 = color.new(color.fuchsia, tp)
// col7 = color.new(color.purple, tp)
// col8 = color.new(color.navy, tp)
// col9 = color.new(color.blue, tp)
// col10 = color.new(color.teal, tp)
// col11 = color.new(color.green, tp)
// col12 = color.new(color.olive, tp)
// col13 = color.new(color.gray, tp)
// col14 = color.new(color.yellow, tp)
// col15 = color.new(color.orange, tp)
// col16 = color.new(color.red, tp)

//plot EMAs
// plot(series=EMA16, title="na/D", style=plot.style_stepline, color=col16)
// plot(series=EMA15, title="na/987", style=plot.style_stepline, color=col15)
// plot(series=EMA14, title="na/610", style=plot.style_stepline, color=col14)
// plot(series=EMA13, title="na/377", style=plot.style_stepline, color=col13)
// plot(series=EMA12, title="M/233", style=plot.style_stepline, color=col12)
// plot(series=EMA11, title="W/144", style=plot.style_stepline, color=col11)
// plot(series=EMA10, title="D/89", style=plot.style_stepline, color=col10)
// plot(series=EMA9, title="8H/55", style=plot.style_stepline, color=col9)
// plot(series=EMA8, title="4H/34", style=plot.style_stepline, color=col8)
// plot(series=EMA7, title="2H/21", style=plot.style_stepline, color=col7)
// plot(series=EMA6, title="60/13", style=plot.style_stepline, color=col6)
plot(series=EMA5, title="30/8", style=plot.style_stepline, color=col5, linewidth=2)
// plot(series=EMA4, title="15/5", style=plot.style_stepline, color=col4)
// plot(series=EMA3, title="5/3", style=plot.style_stepline, color=col3)
// plot(series=EMA2, title="3/2", style=plot.style_stepline, color=col2)
// plot(series=EMA1, title="1/1", style=plot.style_stepline, color=col1)

// END //

shortSma = ta.sma(close, 14)
longSma = ta.sma(close, 28)

longCondition = ta.crossover(shortSma, longSma)
if (longCondition)
    strategy.entry("My Long Entry Id", strategy.long)

shortCondition = ta.crossunder(ta.sma(close, 14), ta.sma(close, 28))
if (shortCondition)
    strategy.entry("My Short Entry Id", strategy.short)

// plot(shortSma, "sma14", color = color.fuchsia)
// plot(longSma, "sma28", color = color.orange)