//@version=5
indicator(title="Buy Low Sell High Composite", shorttitle="BLSH pmac")

// normalize values into the range -1 to +1
normalize(value, minValue, maxValue) =>
    var_range = maxValue - minValue == 0 ? 0.0001 : maxValue - minValue
    -1 + (((value - minValue) / var_range) * 2)

atrValue = ta.atr(9)
priceRange = 2 * atrValue

// RSI
rsiValue = ta.rsi(close, 14)
rsiValueNormalized = normalize(rsiValue, 25, 75)
rsiColor = rsiValueNormalized <= 0 ? color.orange : color.yellow

// Elliot Wave
emaDiff = ta.ema(close, 5) - ta.ema(close, 35)
emaDiffNormalized = normalize(emaDiff, -priceRange, priceRange)
emaColor = emaDiff <= 0 ? color.red : color.lime

// MACD
fastMovingAverage = ta.ema(close, 12)
slowMovingAverage = ta.ema(close, 26)
macd = fastMovingAverage - slowMovingAverage
macdSignal = ta.sma(macd, 9)
macdHistogram = macd - macdSignal
macdNormalized = normalize(macd, -priceRange, priceRange)
macdSignalNormalized = normalize(macdSignal, -priceRange, priceRange)
macdHistogramNormalized = normalize(macdHistogram, -priceRange, priceRange)

isMACDAbove = macd >= macdSignal
crossoverColor = isMACDAbove ? color.lime : color.red
crossoverValue = ta.cross(macd, macdSignal) ? macdSignalNormalized : na

// MFI
positiveFlow = math.sum(volume * (ta.change(hlc3) <= 0 ? 0 : hlc3), 14)
negativeFlow = int(math.sum(volume * (ta.change(hlc3) >= 0 ? 0 : hlc3), 14))
//mfiValue = ta.rsi(positiveFlow, negativeFlow)
// https://www.tradingview.com/pine-script-docs/en/v5/migration_guides/v4_to_v5_migration_guide.html?highlight=mfi
mfiValue = 100.0 - (100.0 / (1.0 + positiveFlow / negativeFlow))
mfiValueNormalized = normalize(mfiValue, 25, 75)

// Composite
compositeValue = emaDiffNormalized + rsiValueNormalized + macdHistogramNormalized + mfiValueNormalized
compositeNormalized = normalize(compositeValue, -4, 4)
compositeColor = compositeValue <= 0 ? color.red : color.lime
compositeStyle = plot.style_histogram

// Plots
plot(compositeNormalized, title="Composite", color=color.new(compositeColor, 50), style=plot.style_area, linewidth=2)
plot(macdSignalNormalized, title="MacD Signal", style=plot.style_line, linewidth=1, color=crossoverColor)
plot(crossoverValue, title="Crossover", style=plot.style_circles, linewidth=3, color=crossoverColor)